# Generated by Django 3.1.2 on 2021-05-31 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInterfaceTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('active', models.BooleanField()),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('title_visible', models.BooleanField()),
                ('logo', models.CharField(blank=True, max_length=100, null=True)),
                ('logo_visible', models.BooleanField()),
                ('css_header_background_color', models.CharField(blank=True, max_length=10, null=True)),
                ('title_color', models.CharField(blank=True, max_length=10, null=True)),
                ('css_header_text_color', models.CharField(blank=True, max_length=10, null=True)),
                ('css_header_link_color', models.CharField(blank=True, max_length=10, null=True)),
                ('css_header_link_hover_color', models.CharField(blank=True, max_length=10, null=True)),
                ('css_module_background_color', models.CharField(blank=True, max_length=10, null=True)),
                ('css_module_text_color', models.CharField(blank=True, max_length=10, null=True)),
                ('css_module_link_color', models.CharField(blank=True, max_length=10, null=True)),
                ('css_module_link_hover_color', models.CharField(blank=True, max_length=10, null=True)),
                ('css_module_rounded_corners', models.BooleanField()),
                ('css_generic_link_color', models.CharField(blank=True, max_length=10, null=True)),
                ('css_generic_link_hover_color', models.CharField(blank=True, max_length=10, null=True)),
                ('css_save_button_background5185', models.CharField(blank=True, max_length=10, null=True)),
                ('css_save_button_backgroundd677', models.CharField(blank=True, max_length=10, null=True)),
                ('css_save_button_text_color', models.CharField(blank=True, max_length=10, null=True)),
                ('css_delete_button_backgroucea0', models.CharField(blank=True, max_length=10, null=True)),
                ('css_delete_button_backgrou6352', models.CharField(blank=True, max_length=10, null=True)),
                ('css_delete_button_text_color', models.CharField(blank=True, max_length=10, null=True)),
                ('css', models.TextField(blank=True, null=True)),
                ('list_filter_dropdown', models.BooleanField()),
                ('related_modal_active', models.BooleanField()),
                ('related_modal_background_color', models.CharField(blank=True, max_length=10, null=True)),
                ('related_modal_rounded_corners', models.BooleanField()),
                ('logo_color', models.CharField(blank=True, max_length=10, null=True)),
                ('recent_actions_visible', models.BooleanField()),
                ('favicon', models.CharField(blank=True, max_length=100, null=True)),
                ('related_modal_background_o7c6e', models.CharField(blank=True, max_length=5, null=True)),
                ('env_name', models.CharField(blank=True, max_length=50, null=True)),
                ('env_visible_in_header', models.BooleanField(blank=True, null=True)),
                ('env_color', models.CharField(blank=True, max_length=10, null=True)),
                ('env_visible_in_favicon', models.BooleanField()),
                ('related_modal_close_button8203', models.BooleanField()),
                ('language_chooser_active', models.BooleanField()),
                ('language_chooser_display', models.CharField(blank=True, max_length=10, null=True)),
                ('list_filter_sticky', models.BooleanField()),
            ],
            options={
                'db_table': 'admin_interface_theme',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('run_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('dvrun', models.CharField(max_length=1)),
                ('pnombre', models.CharField(max_length=50)),
                ('snombre', models.CharField(blank=True, max_length=50, null=True)),
                ('appaterno', models.CharField(max_length=50)),
                ('apmaterno', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('celular', models.CharField(max_length=12)),
                ('correo', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('razon_social', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id_despacho', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_despacho', models.DateField(blank=True, null=True)),
                ('recibido_por', models.CharField(max_length=255)),
                ('direccion_despacho', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=12)),
                ('foto', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'despacho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id_detalle_oc', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_orden_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('valor_unitario', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('tot_linea', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('run_emp', models.IntegerField(primary_key=True, serialize=False)),
                ('dvrun_emp', models.CharField(max_length=1)),
                ('pnombre_emp', models.CharField(max_length=50)),
                ('snombre_emp', models.CharField(blank=True, max_length=50, null=True)),
                ('appaterno_emp', models.CharField(max_length=50)),
                ('apmaterno_emp', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoDespacho',
            fields=[
                ('id_estado_des', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'estado_despacho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoOrdenCompra',
            fields=[
                ('id_estado_orden', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'estado_orden_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FamiliaProducto',
            fields=[
                ('cod_familia', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'familia_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenesCompra',
            fields=[
                ('numorden', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=10)),
                ('fecha_emision', models.DateField()),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ordenes_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_producto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('stock', models.IntegerField()),
                ('stock_critico', models.IntegerField()),
                ('precio', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('cod_proveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('run_proveedor', models.CharField(max_length=10)),
                ('nom_proveedor', models.CharField(max_length=255)),
                ('celular_proveedor', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('cod_tipo_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tipo_cliente', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'tipo_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_documento', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'tipo_documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('cod_tipo_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tipo_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrazabilidadOc',
            fields=[
                ('id_trazabilidad_oc', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'trazabilidad_oc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('num_documento', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('neto', models.IntegerField(blank=True, null=True)),
                ('iva', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField()),
                ('estado', models.CharField(max_length=7)),
                ('id_anulacion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZonaDespacho',
            fields=[
                ('id_zona', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_sector', models.CharField(max_length=50)),
                ('monto_despacho', models.IntegerField()),
            ],
            options={
                'db_table': 'zona_despacho',
                'managed': False,
            },
        ),
    ]
